MenuSemaine_Core/Models/ErrorViewModel.cs
using System;

namespace MenuSemaine_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MenuSemaine_Core/Models/Plat.cs
using MenuSemaine_Core.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MenuSemaine_Core.Models
{
    public class Plat
    {

        public string ID { get; set; }
        public string Name { get; set; }
        public TypePlat Type { get; set; }

    }
}

MenuSemaine_Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MenuSemaine_Core.Models;
using MenuSemaine_Core.Library;
using Microsoft.AspNetCore.Hosting;

namespace MenuSemaine_Core.Controllers
{
    public class HomeController : Controller
    {
        internal readonly MSCDB _db;
        private readonly IHostingEnvironment _env;

        public HomeController(MSCDB mscDB, IHostingEnvironment env)
        {
            this._db = mscDB;
            this._env = env;
        }

        public IActionResult Index()
        {
            var allPlats = new List<Plat>();
            
            using (var db = _db.DataBase(this._env.WebRootPath))
            {
                var plats = db.GetCollection<Plat>("Plats");

                allPlats.AddRange(plats.FindAll());
            }

            return View(allPlats);
        }

        public IActionResult InsertPlat()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InsertPlat([Bind("Name,Type")] Plat plat)
        {
            using (var db = _db.DataBase(this._env.WebRootPath))
            {
                var plats = db.GetCollection<Plat>("Plats");
                plats.Insert(new Plat { ID = Guid.NewGuid().ToString(), Name = plat.Name, Type = plat.Type});
            }

            return ViewComponent("ListPlats");
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MenuSemaine_Core/ViewComponents/ListPlatsViewComponent.cs
namespace MenuSemaine_Core.ViewComponents
{
    using MenuSemaine_Core.Library;
    using MenuSemaine_Core.Models;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class ListPlatsViewComponent : ViewComponent
    {

        internal readonly MSCDB _db;
        private readonly IHostingEnvironment _env;

        public ListPlatsViewComponent(MSCDB mscDB, IHostingEnvironment env)
        {
            this._db = mscDB;
            this._env = env;
        }

        public IViewComponentResult Invoke()
        {
            var allPlats = new List<Plat>();

            using (var db = _db.DataBase(this._env.WebRootPath))
            {
                var plats = db.GetCollection<Plat>("Plats");

                allPlats.AddRange(plats.FindAll());
            }

            return View(allPlats);
        }
    }
}

MenuSemaine_Core/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MenuSemaine_Core/Views/Home/Index.cshtml
@model IEnumerable<MenuSemaine_Core.Models.Plat>

@{
    ViewData["Title"] = "Home Page";
}

<h1>Hello world 2019</h1>
@if (Model.Count() > 0)
{
    <table class="table table-striped rounded bg-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Name</td>
                    <td>@item.Type</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>
        <h1>Not data</h1>
    </p>
}

MenuSemaine_Core/Views/Home/InsertPlat.cshtml
@model MenuSemaine_Core.Models.Plat

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Home" asp-action="InsertPlat"
            data-ajax="true"
            data-ajax-method="POST"
            data-ajax-mode="replace"
            data-ajax-update="#list-plats"
            data-ajax-loading="#divloading">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<MenuSemaine_Core.Library.TypePlat>()"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-outline-primary" role="button"/>
                <a asp-action="Index" class="btn btn-outline-primary" role="button">Annuler</a>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <fieldset class="border p-2">
            <legend class="w-auto"> All Plats</legend>
            <div id="list-plats">
                @await Component.InvokeAsync("ListPlats")
            </div>
        </fieldset>
    </div>
</div>

<div id="divloading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
        top: 0px; width: 100%; height: 100%; background-color:#ffffff; z-index: 300001;
        opacity: .8; filter: alpha(opacity=80);display:none">
    <div style="position: absolute; top: 40%; left: 40%; color: black;">
        <img src="~/images/Wedges.gif" />
    </div>
</div>

MenuSemaine_Core/Views/Shared/Components/ListPlats/Default.cshtml
@model IEnumerable<MenuSemaine_Core.Models.Plat>


<ul class="list-group">

    @foreach (var item in Model)
    {
    <li class="list-group-item list-group-item-action">
        <span>@item.Name</span>
        &nbsp;-&nbsp;
        <span>@item.Type</span>
    </li>
    }
</ul>

MenuSemaine_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MenuSemaine_Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <!-- Online Fonts -->
        <link href="//fonts.googleapis.com/css?family=Share:400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet" />
        <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet" />
        <!-- //Online Fonts -->
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <!-- Online Fonts -->
        <link href="//fonts.googleapis.com/css?family=Share:400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet" />
        <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet" />
        <!-- //Online Fonts -->
    </environment>
</head>
<body>


    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MenuSemaine_Core</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>*@

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MenuSemaine_Core</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js" ></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>